### ISSUE TITLE
What about lockscreen wallpaper.

### ISSUE THREAD

**Issue by BruceZhang1993** [pashazz/ksetwallpaper#1]
Any ideas to change my lockscreen wallpaper?

Can I change it using dbus?

**Comment by BruceZhang1993** [comment]
`kwriteconfig5 --file kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key Image FILE`
If someone need this.

**Comment by pashazz** [comment]
I'd love a pull request if you could. I have no time for this project this year
